Upgrade docusaurus to 3.0.1
cloud-native-taiwan/cloud-native-taiwan.github.io pull request #33
Opened 2023-12-29 04:59 UTC by ching-kuo

Upgrade docusaurus and related package with yarn upgrade command.

2023-12-29 06:09 UTC, tico88612 requested changes

2023-12-29 06:09 UTC, tico88612 commented on yarn.lock
>    version "2.4.1"
This only change `yarn.lock` file, Docusaurus still in v2.4.1

Execute this:
`yarn upgrade @docusaurus/core@latest @docusaurus/preset-classic@latest @docusaurus/module-type-aliases@latest`

2023-12-29 06:11 UTC, ching-kuo commented
Seems like some post having error after upgrade

2024-01-23 07:57 UTC, ching-kuo commented
@tico88612 upgraded to 3.1.0

2024-01-23 12:45 UTC, tico88612 approved these changes

2024-01-23 12:45 UTC, merged