Add Sponsorship Book
cloud-native-taiwan/cloud-native-taiwan.github.io pull request #6
Opened 2022-05-11 10:08 UTC by ching-kuo

This commit the CNTUG sponsorship book and added a link to it in the
website.

2022-05-11 10:16 UTC, steveyiyo requested changes
Thanks to @ching-kuo, But can you add .gitignore to prevent commit `.DS_Store`?

2022-05-11 10:29 UTC, steveyiyo approved these changes

2022-05-14 04:11 UTC, pohsienshih commented
Hi @ching-kuo 

It seems a typo in the first paragraph of the second section of the `cntug_sponsorship_book.pdf`. Maybe change "技術討問" to "技術討論"?

2022-05-15 08:50 UTC, ching-kuo commented
@pohsienshih fixed

2022-05-16 03:23 UTC, pohsienshih commented
@ching-kuo LGTM, Thanks!

2022-05-16 03:24 UTC, pohsienshih approved these changes

2022-05-16 04:02 UTC, ydFu commented
以社群版為主的定期性技術討論與使用者分享，是 CNTUG 對於社群永續經營的目標。
在同時保有社群經營主軸與提供企業透過社群進行宣傳的兩大目標。
CNTUG 提出以贊助方案，進而滿足企業對於宣傳曝光之需求。

下列兩項贊助方案，金額以 NTD 計算，效期為 3 個月:

2022-05-20 07:14 UTC, ching-kuo commented
@ydFu Updated

2022-05-26 07:10 UTC, ydFu commented
LGTM,thanks.

2022-07-18 09:30 UTC, ydFu approved these changes

2022-08-01 15:12 UTC, merged